redoing mender-server

diff --git a/mender-server/backend-tests/run b/mender-server/backend-tests/run
--- a/mender-server/backend-tests/run
+++ b/mender-server/backend-tests/run
@@ -1,35 +1,24 @@
 #!/bin/bash
+set -e
 
-INTEGRATION_PATH=$(git rev-parse --show-toplevel)
+HERE=$(dirname $(readlink -f "$0"))
+INTEGRATION_PATH=$(dirname "$HERE")
 export INTEGRATION_PATH
 
 DOWNLOAD_REQUIREMENTS="true"
 
-COMPOSE_FILES_BASE="-f $INTEGRATION_PATH/backend-tests/docker/docker-compose.backend-tests.yml"
-COMPOSE_FILES_OPEN=" \
+COMPOSE_CMD_OPEN="docker-compose -p backend-tests \
         -f $INTEGRATION_PATH/docker-compose.yml \
         -f $INTEGRATION_PATH/docker-compose.demo.yml \
-        -f $INTEGRATION_PATH/docker-compose.storage.minio.yml \
-        -f $INTEGRATION_PATH/extra/integration-testing/docker-compose.yml \
         -f $INTEGRATION_PATH/backend-tests/docker/docker-compose.backend-tests.yml \
+        -f $INTEGRATION_PATH/docker-compose.storage.minio.yml
         "
-COMPOSE_FILES_ENTERPRISE="${COMPOSE_FILES_OPEN} \
-        -f $INTEGRATION_PATH/docker-compose.enterprise.yml \
+COMPOSE_CMD_ENTERPRISE="${COMPOSE_CMD_OPEN} -f $INTEGRATION_PATH/docker-compose.enterprise.yml \
         -f $INTEGRATION_PATH/extra/recaptcha-testing/tenantadm-test-recaptcha-conf.yml \
-        -f $INTEGRATION_PATH/extra/smtp-testing/workflows-worker-smtp-test.yml \
+        -f $INTEGRATION_PATH/extra/smtp-testing/conductor-workers-smtp-test.yml \
         -f $INTEGRATION_PATH/extra/stripe-testing/stripe-test.docker-compose.yml
         "
-COMPOSE_FILE_STORAGE_AZURE="-f $INTEGRATION_PATH/backend-tests/docker/docker-compose.storage.azblob.yml"
-
-COMPOSE_FILE_AZURE_SETUP="-f $INTEGRATION_PATH/backend-tests/docker/docker-compose.azblob.setup.yml"
-
-COMPOSE_FILES=""
-
-COMPOSE_UP_EXTRA_ARGS="--remove-orphans"
-
-compose_cmd() {
-    docker-compose -p backend-tests $COMPOSE_FILES $@
-}
+COMPOSE_CMD=""
 
 PYTEST_FILTER_OPEN="not Enterprise and not Multitenant"
 PYTEST_FILTER_ENTERPRISE="Enterprise"
@@ -42,8 +31,6 @@ PYTEST_REPORT_ENTERPRISE="--self-contained-html \
         --junit-xml=results_backend_integration_enterprise.xml \
         --html=report_backend_integration_enterprise.html"
 PYTEST_REPORT=""
-
-PYTEST_ARGS=""
 
 TOOLS="$INTEGRATION_PATH/backend-tests/downloaded-tools"
 
@@ -102,11 +89,6 @@ parse_args(){
             -c | --skip-cleanup)
                 SKIP_CLEANUP=1
                 ;;
-            --)
-                shift 1
-                USER_PYTEST_ARGS="$USER_PYTEST_ARGS $@"
-                return 0
-                ;;
             *)
                 USER_PYTEST_ARGS="$USER_PYTEST_ARGS $1"
                 ;;
@@ -115,28 +97,56 @@ parse_args(){
     done
 }
 
-get_runner_requirements() {
-    local MENDER_ARTIFACT_PATH="$TOOLS/mender-artifact"
-    local MENDER_ARTIFACT_BRANCH=$($INTEGRATION_PATH/extra/release_tool.py --version-of mender-artifact)
+build_backend_tests_runner() {
+    mkdir -p "$TOOLS"
 
-    if [ ! -f "$MENDER_ARTIFACT_PATH" ]; then
-        echo "downloading mender-artifact/$MENDER_ARTIFACT_BRANCH"
-        curl -s --fail "https://downloads.mender.io/mender-artifact/${MENDER_ARTIFACT_BRANCH}/linux/mender-artifact" \
-             -o "$MENDER_ARTIFACT_PATH"
-        chmod +x "$MENDER_ARTIFACT_PATH"
+    if [[ -n "$DOWNLOAD_REQUIREMENTS" ]]; then
+        get_runner_requirements
     fi
+
+    docker build -t mender-backend-tests-runner -f $INTEGRATION_PATH/backend-tests/docker/Dockerfile $INTEGRATION_PATH/backend-tests
+}
+
+get_runner_requirements() {
+    MENDER_ARTIFACT_BRANCH=$($INTEGRATION_PATH/extra/release_tool.py --version-of mender-artifact)
+    echo "downloading mender-artifact/$MENDER_ARTIFACT_BRANCH"
+
+    curl --fail "https://d1b0l86ne08fsf.cloudfront.net/mender-artifact/${MENDER_ARTIFACT_BRANCH}/linux/mender-artifact" \
+         -o "$TOOLS/mender-artifact"
+
+    chmod +x "$TOOLS/mender-artifact"
 }
 
 run_tests() {
-    local RUN_ARGS="--use-aliases"
-    # Need to start the backend first
-    compose_cmd up $COMPOSE_UP_EXTRA_ARGS --scale mender-backend-tests-runner=0 -d
-    if [ -n "$AZURE_IOTHUB_CONNECTIONSTRING" ]; then
-        RUN_ARGS="${RUN_ARGS} -e AZURE_IOTHUB_CONNECTIONSTRING=${AZURE_IOTHUB_CONNECTIONSTRING}"
+    $COMPOSE_CMD up -d
+
+    cid=""
+    declare retries=5
+    while [[ $retries -gt 0 && -z $cid ]]; do
+        cid=$(get_container_id mender-backend-tests-runner)
+        sleep 1
+        retries=$((retries-1))
+    done
+
+    if [[ -z $cid ]]; then
+        echo "failed to get container id"
+        return 1
     fi
-    # ... then the runner
-    compose_cmd run $RUN_ARGS mender-backend-tests-runner
-    return $?
+
+    run_tests_failed=""
+    docker attach $cid || run_tests_failed=1
+    rc=$(get_container_exit_code $cid)
+    if [ "$run_tests_failed" != "1" ] && [ "$rc" != "0" ]; then
+        run_tests_failed=$rc
+    fi
+}
+
+get_container_id() {
+    echo "$(docker ps --filter label=com.docker.compose.service=$1 -q)"
+}
+
+get_container_exit_code() {
+    echo "$(docker inspect --format '{{.State.ExitCode}}' $1 || echo 1)"
 }
 
 copy_test_reports_if_args() {
@@ -160,7 +170,6 @@ copy_test_reports_if_args() {
         shift
     done
 
-    cid=$(compose_cmd ps -aq mender-backend-tests-runner | head -n 1)
     if [ -n "$RESULTS_FILE" ]; then
         echo "-- copying file $RESULTS_FILE"
         docker cp ${cid}:/$RESULTS_FILE . || true
@@ -172,6 +181,7 @@ copy_test_reports_if_args() {
 }
 
 prepare_pytest_args() {
+    PYTEST_ARGS=""
     filter="none"
     for val in $USER_PYTEST_ARGS; do
         if [ "$val" == "-k" ]; then
@@ -191,79 +201,35 @@ prepare_pytest_args() {
 }
 
 cleanup(){
-    if [ -z $SKIP_CLEANUP ]; then
-        compose_cmd down -v --remove-orphans
-    else
-        # Remove stopped container created by docker-compose run
-        compose_cmd rm -f
-    fi
-    if [ -n "$AZURE_STORAGE_CONTAINER_PREFIX" ]; then
-        # Remove the blob storage container if we created one
-        echo "Removing blob storage container '$AZURE_STORAGE_CONTAINER_NAME'"
-        docker-compose $COMPOSE_FILE_AZURE_SETUP run --rm \
-                       azblob-container-teardown $AZURE_STORAGE_CONTAINER_NAME
-        docker-compose $COMPOSE_FILE_AZURE_SETUP down
-    fi
+    [ -z $SKIP_CLEANUP ] && $COMPOSE_CMD down -v --remove-orphans && $COMPOSE_CMD rm || true
 }
 
 parse_args "$@"
-mkdir -p "$TOOLS"
+build_backend_tests_runner
 
-if [[ -n "$DOWNLOAD_REQUIREMENTS" ]]; then
-    get_runner_requirements
-fi
-
-script_failed=0
 
 for suite in "${TEST_SUITES[@]}"; do
     case "$suite" in
         open)
-            COMPOSE_FILES="$COMPOSE_FILES_OPEN"
+            COMPOSE_CMD="$COMPOSE_CMD_OPEN"
             PYTEST_FILTER="$PYTEST_FILTER_OPEN"
             PYTEST_REPORT="$PYTEST_REPORT_OPEN"
             ;;
         enterprise)
-            COMPOSE_FILES="$COMPOSE_FILES_ENTERPRISE"
+            COMPOSE_CMD="$COMPOSE_CMD_ENTERPRISE"
             PYTEST_FILTER="$PYTEST_FILTER_ENTERPRISE"
             PYTEST_REPORT="$PYTEST_REPORT_ENTERPRISE"
             ;;
     esac
 
-    # Are we running in Azure mode?
-    if [ -n "$AZURE_STORAGE_CONTAINER_PREFIX" ]; then
-        # Create a container (bucket) will be removed in cleanup
-        rand_suffix=$(cat /dev/urandom | tr -dc 'a-z' | head -c 8)
-        date_suffix=$(date '+%Y%m%d-%H%M%S')
-        container="${AZURE_STORAGE_CONTAINER_PREFIX}-${date_suffix}-${rand_suffix}"
-        export AZURE_STORAGE_CONTAINER_NAME="${container}"
-        echo "Creating container '$AZURE_STORAGE_CONTAINER_NAME'"
-        docker-compose $COMPOSE_FILE_AZURE_SETUP run --rm \
-                       azblob-container-setup $AZURE_STORAGE_CONTAINER_NAME
-        ec=$?
-        if [ $ec -ne 0 ]; then
-            echo -n 'Failed to setup blob storage for testing'
-            exit $ec
-        fi
-    fi
-    if [ -n "$K8S" ]; then
-        COMPOSE_FILES="${COMPOSE_FILES_BASE}"
-    elif [ -n "$AZURE_STORAGE_CONTAINER_NAME" ]; then
-        COMPOSE_FILES="${COMPOSE_FILES} ${COMPOSE_FILE_STORAGE_AZURE}"
-        COMPOSE_UP_EXTRA_ARGS="${COMPOSE_UP_EXTRA_ARGS} --scale minio=0"
-        PYTEST_ARGS="$PYTEST_ARGS -m storage_test"
-    fi
-
     prepare_pytest_args
     run_tests
-    run_tests_retcode=$?
-    if [ $script_failed -eq 0 ]; then
-        script_failed=$run_tests_retcode
-    fi
 
-    if [ $run_tests_retcode -ne 0 ]; then
-        tmppath=$(mktemp -p . acceptance.XXXXXX)
+    if [ "$run_tests_failed" != "" ]; then
+        script_failed=$run_tests_failed
+        tmppath=$(mktemp ${HERE}/acceptance.XXXXXX)
         echo "-- tests failed, dumping logs to $tmppath"
-        compose_cmd logs > "$tmppath" 2>&1
+        $COMPOSE_CMD logs > $tmppath
     fi
 
     copy_test_reports_if_args $PYTEST_REPORT
