broke

diff --git a/mender-server/backend-tests/run b/mender-server/backend-tests/run
--- a/mender-server/backend-tests/run
+++ b/mender-server/backend-tests/run
@@ -1,121 +1,240 @@
 #!/bin/bash
-set -e
 
 HERE=$(dirname $(readlink -f "$0"))
 INTEGRATION_PATH=$(dirname "$HERE")
 export INTEGRATION_PATH
 
-COMPOSE_CMD="docker-compose -p backend-tests \
-             -f $INTEGRATION_PATH/docker-compose.yml \
-             -f $INTEGRATION_PATH/docker-compose.demo.yml \
-             -f $INTEGRATION_PATH/backend-tests/docker/docker-compose.backend-tests.yml"
+DOWNLOAD_REQUIREMENTS="true"
 
-# by default just add minio, with COMPOSE_CMD_BASE this creates the standard onprem ST setup
-COMPOSE_FILES_DEFAULT=( "$INTEGRATION_PATH/docker-compose.storage.minio.yml" )
-COMPOSE_FILES=()
+COMPOSE_CMD_BASE="docker-compose -p backend-tests \
+        -f $INTEGRATION_PATH/backend-tests/docker/docker-compose.backend-tests.yml
+        "
+COMPOSE_CMD_OPEN="docker-compose -p backend-tests \
+        -f $INTEGRATION_PATH/docker-compose.yml \
+        -f $INTEGRATION_PATH/docker-compose.demo.yml \
+        -f $INTEGRATION_PATH/docker-compose.storage.minio.yml
+        -f $INTEGRATION_PATH/extra/integration-testing/docker-compose.yml
+        -f $INTEGRATION_PATH/backend-tests/docker/docker-compose.backend-tests.yml
+        "
+COMPOSE_CMD_ENTERPRISE="${COMPOSE_CMD_OPEN} \
+        -f $INTEGRATION_PATH/docker-compose.enterprise.yml \
+        -f $INTEGRATION_PATH/extra/recaptcha-testing/tenantadm-test-recaptcha-conf.yml \
+        -f $INTEGRATION_PATH/extra/smtp-testing/workflows-worker-smtp-test.yml \
+        -f $INTEGRATION_PATH/extra/stripe-testing/stripe-test.docker-compose.yml
+        "
+COMPOSE_CMD=""
+
+PYTEST_FILTER_OPEN="not Enterprise and not Multitenant"
+PYTEST_FILTER_ENTERPRISE="Enterprise"
+PYTEST_FILTER=""
+
+PYTEST_REPORT_OPEN="--self-contained-html \
+        --junit-xml=results_backend_integration_open.xml \
+        --html=report_backend_integration_open.html"
+PYTEST_REPORT_ENTERPRISE="--self-contained-html \
+        --junit-xml=results_backend_integration_enterprise.xml \
+        --html=report_backend_integration_enterprise.html"
+PYTEST_REPORT=""
+
+TOOLS="$INTEGRATION_PATH/backend-tests/downloaded-tools"
 
 usage() {
     echo "runner script for backend-specific integration tests"
     echo ""
     echo "./backend-tests"
     echo -e "\t-h --help"
+    echo -e "\t-s --suite <SUITE>\trun specific test suite"
+    echo -e "\t                  \t<SUITE> can be 'open' (default), 'enterprise', 'all'"
+    echo -e "\t--no-download     \tdo not download the external dependencies"
     echo -e "\t-c --skip-cleanup \tleave containers running after tests"
-    echo -e "\t-f=<FILE>         \tspecify custom compose file(s); default files will not be used,"
-    echo -e "\t                  \tmake sure to specify all files you need"
     echo -e "\t other args will be passed to the testing container's py.test command"
     echo ""
     echo -e "examples:"
-    echo -e "run all tests, default ST setup:"
+    echo -e "run default ST setup:"
     echo -e "\t./run"
-    echo -e "run tests matching expression 'multitenant'"
-    echo -e "\t./run -k multitenant"
+    echo -e "run tests Enterprise tests"
+    echo -e "\t./run -s enterprise"
+    echo -e "run specific test TestGetDevices in both setups"
+    echo -e "\t./run -s all -k TestGetDevices"
 }
 
+TEST_SUITES=( "open" )
 parse_args(){
-    whitespace="[[:space:]]"
-
-    # FIXME args must be passed in the form -f=<path>; spaces don't workalthough they're standard...
     while [ $# -gt 0 ]; do
-        PARAM=`echo $1 | awk -F= '{print $1}'`
-        VALUE=`echo $1 | awk -F= '{print $2}'`
-        case $PARAM in
+        case "$1" in
             -h | --help)
-            usage
-            exit
-            ;;
+                usage
+                exit
+                ;;
+            -s | --suite)
+                shift 1
+                case "$1" in
+                    open)
+                        ;;
+                    enterprise)
+                        TEST_SUITES=( "enterprise" )
+                        ;;
+                    all)
+                        TEST_SUITES=( "open" "enterprise" )
+                        ;;
+                    *)
+                        usage
+                        exit
+                        ;;
+                esac
+                ;;
+            -f | -f=*)
+                usage
+                exit 1
+                ;;
+            --no-download)
+                DOWNLOAD_REQUIREMENTS=""
+                ;;
             -c | --skip-cleanup)
-            SKIP_CLEANUP=1
-            ;;
-            -f)
-            COMPOSE_FILES+=( $VALUE )
-            ;;
+                SKIP_CLEANUP=1
+                ;;
+            --)
+                shift 1
+                USER_PYTEST_ARGS="$USER_PYTEST_ARGS $@"
+                return 0
+                ;;
             *)
+                USER_PYTEST_ARGS="$USER_PYTEST_ARGS $1"
+                ;;
         esac
         shift 1
     done
-
-    make_compose_cmd
 }
 
-make_compose_cmd () {
-    if [ ${#COMPOSE_FILES[@]} -eq 0 ]
-    then
-        COMPOSE_FILES=$COMPOSE_FILES_DEFAULT
+get_runner_requirements() {
+    local MENDER_ARTIFACT_PATH="$TOOLS/mender-artifact"
+    local MENDER_ARTIFACT_BRANCH=$($INTEGRATION_PATH/extra/release_tool.py --version-of mender-artifact)
+
+    if [ ! -f "$MENDER_ARTIFACT_PATH" ]; then
+        echo "downloading mender-artifact/$MENDER_ARTIFACT_BRANCH"
+        curl -s --fail "https://downloads.mender.io/mender-artifact/${MENDER_ARTIFACT_BRANCH}/linux/mender-artifact" \
+             -o "$MENDER_ARTIFACT_PATH"
+        chmod +x "$MENDER_ARTIFACT_PATH"
     fi
-
-    for var in "${COMPOSE_FILES[@]}"
-    do
-        COMPOSE_CMD+=" -f ${var}"
-    done
-}
-
-build_backend_tests_runner() {
-    docker build -t mender-backend-tests-runner -f $INTEGRATION_PATH/backend-tests/docker/Dockerfile $INTEGRATION_PATH/backend-tests
 }
 
 run_tests() {
-    $COMPOSE_CMD up -d
+    local RUN_ARGS="--use-aliases"
+    # Need to start the backend first
+    $COMPOSE_CMD up --scale mender-backend-tests-runner=0 -d --remove-orphans
+    if [ -n "$AZURE_IOTHUB_CONNECTIONSTRING" ]; then
+        RUN_ARGS="${RUN_ARGS} -e AZURE_IOTHUB_CONNECTIONSTRING=${AZURE_IOTHUB_CONNECTIONSTRING}"
+    fi
+    # ... then the runner
+    $COMPOSE_CMD run $RUN_ARGS mender-backend-tests-runner
+    return $?
+}
 
-    declare retries=5
-    while [[ $retries -gt 0 && -z $cid ]]; do
-        cid=$(get_container_id mender-backend-tests-runner)
-        sleep 1
-        retries=$((retries-1))
+copy_test_reports_if_args() {
+    while [ -n "$1" ]; do
+        case "$1" in
+            --junit-xml=*)
+                RESULTS_FILE="${1#--junit-xml=}"
+                ;;
+            --junit-xml)
+                shift
+                RESULTS_FILE="$1"
+                ;;
+            --html=*)
+                REPORT_FILE="${1#--html=}"
+                ;;
+            --html)
+                shift
+                REPORT_FILE="$1"
+                ;;
+        esac
+        shift
     done
 
-    if [[ -z $cid ]]; then
-        echo "failed to get container id"
-        return 1
+    cid=$($COMPOSE_CMD ps -aq mender-backend-tests-runner | head -n 1)
+    if [ -n "$RESULTS_FILE" ]; then
+        echo "-- copying file $RESULTS_FILE"
+        docker cp ${cid}:/$RESULTS_FILE . || true
     fi
-
-    docker attach $cid || failed=1
-
-    get_container_exit_code $cid || true
-    [ $? == 0 ] || failed=1
+    if [ -n "$REPORT_FILE" ]; then
+        echo "-- copying file $REPORT_FILE"
+        docker cp ${cid}:/$REPORT_FILE . || true
+    fi
 }
 
-get_container_id() {
-    echo "$(docker ps --filter label=com.docker.compose.service=$1 -q)"
-}
+prepare_pytest_args() {
+    PYTEST_ARGS=""
+    filter="none"
+    for val in $USER_PYTEST_ARGS; do
+        if [ "$val" == "-k" ]; then
+            filter="next"
+        elif [ "$filter" == "next" ]; then
+            PYTEST_FILTER="$PYTEST_FILTER and $val"
+            filter="done"
+        else
+            PYTEST_ARGS="$PYTEST_ARGS $val"
+        fi
+    done
 
-get_container_exit_code() {
-    docker inspect --format '{{.State.ExitCode}}' $1
+    echo "-- using PYTEST_FILTER=$PYTEST_FILTER"
+    PYTEST_ARGS="$PYTEST_ARGS -k '$PYTEST_FILTER' $PYTEST_REPORT"
+
+    export PYTEST_ARGS
 }
 
 cleanup(){
-    [ -z $SKIP_CLEANUP ] && $COMPOSE_CMD down && $COMPOSE_CMD rm || true
+    if [ -z $SKIP_CLEANUP ]; then
+        $COMPOSE_CMD down -v --remove-orphans
+    else
+        # Remove stopped container created by docker-compose run
+        $COMPOSE_CMD rm -f
+    fi
 }
 
 parse_args "$@"
-build_backend_tests_runner
-run_tests
+mkdir -p "$TOOLS"
 
-if [ -n "$failed" ]; then
-    tmppath=$(mktemp /tmp/acceptance.XXXXXX)
-    echo "-- tests failed, dumping logs to $tmppath"
-    $COMPOSE_CMD logs > $tmppath
+if [[ -n "$DOWNLOAD_REQUIREMENTS" ]]; then
+    get_runner_requirements
 fi
 
-cleanup
+script_failed=0
 
-exit $failed
+for suite in "${TEST_SUITES[@]}"; do
+    case "$suite" in
+        open)
+            COMPOSE_CMD="$COMPOSE_CMD_OPEN"
+            PYTEST_FILTER="$PYTEST_FILTER_OPEN"
+            PYTEST_REPORT="$PYTEST_REPORT_OPEN"
+            ;;
+        enterprise)
+            COMPOSE_CMD="$COMPOSE_CMD_ENTERPRISE"
+            PYTEST_FILTER="$PYTEST_FILTER_ENTERPRISE"
+            PYTEST_REPORT="$PYTEST_REPORT_ENTERPRISE"
+            ;;
+    esac
+
+    if [ -n "$K8S" ]; then
+        COMPOSE_CMD="${COMPOSE_CMD_BASE}"
+    fi
+
+    prepare_pytest_args
+    run_tests
+    run_tests_retcode=$?
+    if [ $script_failed -eq 0 ]; then
+        script_failed=$run_tests_retcode
+    fi
+
+    if [ $run_tests_retcode -ne 0 ]; then
+        tmppath=$(mktemp ${HERE}/acceptance.XXXXXX)
+        echo "-- tests failed, dumping logs to $tmppath"
+        $COMPOSE_CMD logs > $tmppath
+    fi
+
+    copy_test_reports_if_args $PYTEST_REPORT
+
+    cleanup
+
+done
+
+exit $script_failed
diff --git a/mender-server/keygen b/mender-server/keygen
--- a/mender-server/keygen
+++ b/mender-server/keygen
@@ -1,74 +1,106 @@
 #!/bin/bash
 set -e
 
-if [ -z "$CERT_API_CN" ] || [ -z "$CERT_STORAGE_CN" ] ; then
-    echo "Environment variables CERT_API_CN and CERT_STORAGE_CN need to be set."
-    echo "Example: CERT_API_CN=\"docker.mender.io\" CERT_STORAGE_CN=\"s3.docker.mender.io\" $0"
-    exit 1
+_CMD=$0
+
+show_help() {
+    cat <<EOF
+Usage: ${_CMD} [--help]
+
+Generate self-signed certificate and JWT authentication keys for the Mender server.
+
+Environment variables:
+    CERT_CN  - Certificate common name
+    CERT_SAN - Comma separated list of certificate subject alternative names (SANs)
+               See openssl-req(1)
+EOF
+}
+
+while [ $# -gt 0 ]; do
+    case ${1} in
+    --help)
+        show_help
+        exit 0
+        break;;
+    *)
+        echo 'Unrecognized commandline argument "'${1}'"'
+        show_help
+        exit 1
+        break;;
+    esac
+    shift 1
+done
+
+# Verify dependencies
+CLI_COMMANDS="cut sed sort head"
+for cmd in ${CLI_COMMANDS}; do
+  command -v ${cmd} &>/dev/null || { echo >&2 "ERROR: Please install the '${cmd}' utility to generate key configuration."; exit 1; }
+done
+
+# verify openssl is present and sufficiently recent (genpkey seems to require openssl 1.1.1+)
+OPENSSL_VERSION_MINIMAL="1.1.1"
+command -v openssl >/dev/null 2>&1 || { echo >&2 "ERROR: Please install the openssl utility version ${OPENSSL_VERSION_MINIMAL} or newer to generate keys."; exit 1; }
+OPENSSL_VERSION=$(openssl version | cut -d' ' -f2 | sed 's~[a-z]~~g')
+if [[ "${OPENSSL_VERSION_MINIMAL}" != "$(printf "${OPENSSL_VERSION_MINIMAL}\n${OPENSSL_VERSION}" | sort -V | head -n 1)" ]]; then
+  echo "ERROR: openssl version '${OPENSSL_VERSION}' is too old, need version ${OPENSSL_VERSION_MINIMAL} or newer"
+  exit 1
+fi
+
+if [ -z "${CERT_CN}" ]; then
+    echo "Common name (CERT_CN) not set."
+    echo -n "Enter a certificate common name [docker.mender.io]:"
+    IFS='' read -r CERT_CN
+    if [ -z "${CERT_CN}" ]; then
+        CERT_CN="docker.mender.io"
+    fi
+fi
+
+if [ -z "${CERT_SAN}" ]; then
+    CERT_SAN="DNS:${CERT_CN},DNS:*.${CERT_CN}"
+    echo "Subject alternative name (CERT_SAN) not set, using default:"
+    echo "    CERT_SAN=\"${CERT_SAN}\""
 fi
 
 CERT_VALID_DAYS="3650"
 FILE_NAME_PRIVATE_KEY="private.key"
 FILE_NAME_CERT="cert.crt"
 
-
-# verify openssl is present and sufficiently recent (genpkey seems to require openssl 1.0+)
-command -v openssl >/dev/null 2>&1 || { echo >&2 "ERROR: Please install the openssl utility version 1.0.0 or newer to generate keys."; exit 1; }
-
-OPENSSL_VERSION_REGEX_MAJOR_BACKREF="OpenSSL ([0-9]+).*"
-OPENSSL_VERSION_STRING=$(openssl version)
-OPENSSL_VERSION_MAJOR=$(echo "$OPENSSL_VERSION_STRING" | sed -En "s/$OPENSSL_VERSION_REGEX_MAJOR_BACKREF/\1/p")
-
-if [ "$OPENSSL_VERSION_MAJOR" != "1" ]; then
-  echo "ERROR: openssl is too old, need version 1.0.0 or newer"
-  echo "ERROR: OPENSSL_VERSION_STRING=$OPENSSL_VERSION_STRING"
-  exit 1
-fi
-
-
 ROOTDIR=$(pwd)/keys-generated
 
-CERTDIR=$ROOTDIR/certs
-KEYDIR=$ROOTDIR/keys
+CERTDIR=${ROOTDIR}/cert
+KEYDIR=${ROOTDIR}/keys
 
 
-# generate web certs and corresponding private keys
+# generate web cert and corresponding private key
+mkdir -p "${CERTDIR}"
+cd "${CERTDIR}"
 
-mkdir -p "$CERTDIR"
-cd "$CERTDIR"
-
-mkdir api-gateway storage-proxy
-
-cd api-gateway
-openssl req -x509 -sha256 -nodes -days $CERT_VALID_DAYS -newkey ec:<(openssl ecparam -name prime256v1) -keyout $FILE_NAME_PRIVATE_KEY -out $FILE_NAME_CERT -subj /CN="$CERT_API_CN"
-cd ..
-
-cd storage-proxy
-openssl req -x509 -sha256 -nodes -days $CERT_VALID_DAYS -newkey ec:<(openssl ecparam -name prime256v1) -keyout $FILE_NAME_PRIVATE_KEY -out $FILE_NAME_CERT -subj /CN="$CERT_STORAGE_CN"
-cd ..
-
-# concatenate the certificates for inclusion on the Mender client
-cat api-gateway/$FILE_NAME_CERT storage-proxy/$FILE_NAME_CERT > server.crt
-
+openssl req -x509 -sha256 -nodes \
+    -days ${CERT_VALID_DAYS} \
+    -newkey ec:<(openssl ecparam -name prime256v1) \
+    -keyout ${FILE_NAME_PRIVATE_KEY} \
+    -out ${FILE_NAME_CERT} \
+    -subj "/CN=${CERT_CN}" \
+    -addext "extendedKeyUsage = serverAuth" \
+    -addext "subjectAltName = ${CERT_SAN}"
 
 # generate keys for signing JSON Web Tokens
-
-mkdir -p "$KEYDIR"
-cd "$KEYDIR"
+mkdir -p "${KEYDIR}"
+cd "${KEYDIR}"
 
 for DIR in deviceauth useradm
 do
-  mkdir $DIR
+  mkdir -p ${DIR}
   (
-    cd $DIR
-    openssl genpkey -algorithm RSA -out $FILE_NAME_PRIVATE_KEY -pkeyopt rsa_keygen_bits:3072
+    cd ${DIR}
+    openssl genpkey -algorithm RSA -out ${FILE_NAME_PRIVATE_KEY} -pkeyopt rsa_keygen_bits:3072
 
     # convert to RSA private key format, otherwise services complain:"
     # level=fatal msg="failed to read rsa private key: jwt: can't open key - not an rsa private key" file=proc.go func=runtime.main line=183
-    openssl rsa -in $FILE_NAME_PRIVATE_KEY -out $FILE_NAME_PRIVATE_KEY
+    openssl rsa -in ${FILE_NAME_PRIVATE_KEY} -out ${FILE_NAME_PRIVATE_KEY}
   )
 done
 
-echo "All Mender Server keys and certificates have been generated in directory $ROOTDIR."
+echo "All Mender Server keys and certificates have been generated in directory ${ROOTDIR}."
 echo "Please include them in your docker compose and device builds."
-echo "For more information please see https://docs.mender.io/Administration/Certificates-and-keys."
+echo "For more information, please refer to https://docs.mender.io/"
diff --git a/mender-server/verify-docker-versions b/mender-server/verify-docker-versions
--- a/mender-server/verify-docker-versions
+++ b/mender-server/verify-docker-versions
@@ -8,11 +8,21 @@ VERSION_MINOR_MIN_DOCKER_ENGINE="11"
 VERSION_MINOR_MIN_DOCKER_COMPOSE="6"
 
 compare_versions() {
-  VERSION_ACTUAL=$1
-  VERSION_MINIMUM=$2
+  VERSION_MAJOR=$1
+  VERSION_ACTUAL=$2
+  VERSION_MINIMUM=$3
 
   if [[ -z $VERSION_ACTUAL ]]; then
     echo "ERROR: Actual version is empty (hint: is it installed, or version format change?)."
+    return 1
+  fi
+
+  if [ "$VERSION_MAJOR" == "2" ]; then
+    return 0
+  fi
+
+  if [ "$VERSION_MAJOR" != "1" ]; then
+    echo "ERROR: Unsupported major version: $VERSION_MAJOR"
     return 1
   fi
 
@@ -24,10 +34,21 @@ compare_versions() {
   return 0
 }
 
+# test that user has rights to use docker
+
+DOCKER_ENGINE_INFO_STDERR=$(docker info 2>&1 >/dev/null)
+DOCKER_ENGINE_INFO_RETVAL=$?
+if [[ $DOCKER_ENGINE_INFO_RETVAL -ne 0 ]]; then
+  >&2 echo "Local user has insufficient permissions to connect to the docker daemon."
+  >&2 echo "Please add user to 'docker' group to be able to access it or check the documentation for your host OS."
+  >&2 echo "Be aware that if you were just added to the group, you need to log out and in again."
+  >&2 echo $DOCKER_ENGINE_INFO_STDERR
+  exit 1
+fi
 
 # test Docker Engine version
 
-DOCKER_ENGINE_VERSION_STRING=$(sudo docker info 2>/dev/null | grep "Server Version")
+DOCKER_ENGINE_VERSION_STRING=$(docker info 2>/dev/null | grep "Server Version")
 
 DOCKER_ENGINE_VERSION_NEW_SCHEME_REGEX="Server Version: ([0-9]{2,})|([2-9]+)\.[0-9]+\.[0-9]+"
 
@@ -53,14 +74,15 @@ fi
 
 # test Docker Compose version
 
-DOCKER_COMPOSE_VERSION_REGEX_MINOR_BACKREF="1\.([0-9]+)\.[0-9]+"
+DOCKER_COMPOSE_VERSION_REGEX_BACKREF="v?([0-9]+)\.([0-9]+)\.[0-9]+"
 DOCKER_COMPOSE_VERSION_STRING=$(docker-compose version --short)
-DOCKER_COMPOSE_VERSION_MINOR=$(echo "$DOCKER_COMPOSE_VERSION_STRING" | sed -En "s/$DOCKER_COMPOSE_VERSION_REGEX_MINOR_BACKREF/\1/p")
+DOCKER_COMPOSE_VERSION_MAJOR=$(echo "$DOCKER_COMPOSE_VERSION_STRING" | sed -En "s/$DOCKER_COMPOSE_VERSION_REGEX_BACKREF/\1/p")
+DOCKER_COMPOSE_VERSION_MINOR=$(echo "$DOCKER_COMPOSE_VERSION_STRING" | sed -En "s/$DOCKER_COMPOSE_VERSION_REGEX_BACKREF/\2/p")
 
-compare_versions "$DOCKER_COMPOSE_VERSION_MINOR" "$VERSION_MINOR_MIN_DOCKER_COMPOSE"
+compare_versions "$DOCKER_COMPOSE_VERSION_MAJOR" "$DOCKER_COMPOSE_VERSION_MINOR" "$VERSION_MINOR_MIN_DOCKER_COMPOSE"
 
 if [ $? -ne 0 ]; then
-  echo "ERROR: Docker Compose must be on version 1.$VERSION_MINOR_MIN_DOCKER_COMPOSE or larger, but found version 1.$DOCKER_COMPOSE_VERSION_MINOR installed."
+  echo "ERROR: Docker Compose must be on version 1.$VERSION_MINOR_MIN_DOCKER_COMPOSE or larger, but found version ${DOCKER_COMPOSE_VERSION_STRING} installed."
   echo "DOCKER_COMPOSE_VERSION_STRING=$DOCKER_COMPOSE_VERSION_STRING"
   exit 1
 fi
